# Generated by Django 6.1.1 on 2026-09-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва')),
                ('head', models.CharField(max_length=200, verbose_name='завідувач кафедри')),
            ],
            options={
                'verbose_name': 'кафедра',
                'verbose_name_plural': 'кафедри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва факультету')),
                ('description', models.TextField(verbose_name='опис факультету')),
                ('dean', models.CharField(max_length=200, verbose_name='декан')),
                ('address', models.CharField(max_length=300, verbose_name='адреса')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='електронна пошта')),
            ],
            options={
                'verbose_name': 'інформація про факультет',
                'verbose_name_plural': 'інформація про факультет',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва')),
                ('code', models.CharField(max_length=20, verbose_name='код')),
                ('description', models.TextField(verbose_name='опис')),
                ('coordinator_name', models.CharField(max_length=200, verbose_name='координатор набору')),
                ('coordinator_contact', models.CharField(max_length=200, verbose_name='контакт координатора')),
                ('disciplines', models.TextField(blank=True, help_text='Кожна дисципліна з нового рядка.', verbose_name='список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='faculty.department', verbose_name='випускова кафедра')),
            ],
            options={
                'verbose_name': 'спеціальність',
                'verbose_name_plural': 'спеціальності',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="ім'я")),
                ('position', models.CharField(max_length=200, verbose_name='посада')),
                ('degree', models.CharField(blank=True, max_length=200, verbose_name='науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='faculty.department', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'викладач',
                'verbose_name_plural': 'викладачі',
                'ordering': ['name'],
            },
        ),
    ]
