# Generated by Django 6.1.1 on 2026-09-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_load_dean_office_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='країна'),
        ),
    ]
