# Generated by Django 6.1.1 on 2026-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_split_university_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
